# Server Configuration
server.port=10333
server.address=0.0.0.0

# Application Name
spring.application.name=otel-observer-receiver

# Elasticsearch Configuration
spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.socket-timeout=30s
spring.elasticsearch.connection-timeout=10s

# Actuator Endpoints
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
